config/routes.rb
Nubeporra::Application.routes.draw do

  resources :boxings do
  end

  devise_for :users

  resources :games do
    resources :bets
  end

  resources :scoretypes do
    resources :scoretypevalues
  end

  root :to =>            'static_pages#home'

  get '/home',     to: 'static_pages#home'
  get '/live',     to: 'static_pages#live'
  get '/analysis',     to: 'static_pages#analysis'

  get '/users/:id/bets',  to: 'bets#user'

  get '/boxing/:id/standing',  to: 'boxings#standing', as: :standing_boxing
  get '/boxing/:id/betting',  to: 'boxings#betting', as: :betting_boxing
  post '/boxing/:id/betting',  to: 'boxings#import', as: :boxing_import

  get '/scores/acb',  to: 'scoreapis#acb', as: :acb
  get '/scores/:date/acb/edit',  to: 'scoreapis#acb_edit', as: :acb_edit
  post '/scores/acb/edit',  to: 'games#import', as: :acb_import

  get '/scores/asobal',  to: 'scoreapis#asobal', as: :asobal
  get '/scores/:date/asobal/edit',  to: 'scoreapis#asobal_edit', as: :asobal_edit
  post '/scores/asobal/edit',  to: 'games#import', as: :asobal_import

  get '/scores/futsal',  to: 'scoreapis#futsal', as: :futsal
  get '/scores/:date/futsal/edit',  to: 'scoreapis#futsal_edit', as: :futsal_edit
  post '/scores/futsal/edit',  to: 'games#import', as: :futsal_import

  get '/scores/nba',  to: 'scoreapis#nba', as: :nba
  get '/scores/:date/nba/edit',  to: 'scoreapis#nba_edit', as: :nba_edit
  post '/scores/:date/nba/edit',  to: 'games#import', as: :nba_import

  get '/scores/football',  to: 'scoreapis#football', as: :football

  get '/scores/:date/football/edit',  to: 'scoreapis#football_edit', as: :football_edit
  post '/scores/:date/football/edit',  to: 'games#import', as: :football_import

 

end

app/controllers/scoreapis_controller.rb
class ScoreapisController < ApplicationController
  include HTTParty
  include Nokogiri

  def football
    @games = []
    if !params[:realDate]
      @realDate = Time.now()
    else 
      @realDate = Date.new(params[:realDate][:year].to_i,params[:realDate][:month].to_i,params[:realDate][:day].to_i)
    end
    @date = @realDate.strftime('%Y-%m-%d')
    games = api_football('matchsday', 'date=' + @date)
    @games = games.parsed_response['matches'] if games.parsed_response['matches']
  end

  def nba
    @games = []
    if !params[:realDate]
      @realDate = Time.now()
      @offset = 0
    else 
      @realDate = Date.new(params[:realDate][:year].to_i,params[:realDate][:month].to_i,params[:realDate][:day].to_i)
      @offset = (@realDate - Date.today).to_i
    end
    games = api_nba('season/scoreScheduleByDate', 'gameDateOffset=' + @offset.to_s)
    @games = games.parsed_response['Schedule']['League']['Game'] if games.parsed_response['Schedule']['League']['Game']
  end

  def acb
    @games = []
    if !params[:realDate]
      @realDate = Time.now()
    else 
      @realDate = Date.new(params[:realDate][:year].to_i,params[:realDate][:month].to_i,params[:realDate][:day].to_i)
    end
    @games = api_acb('','').select{|game| game['date'] == @realDate}
  end

  def asobal
    if !params[:realDate]
      @realDate = Time.now()
    else 
      @realDate = Date.new(params[:realDate][:year].to_i,params[:realDate][:month].to_i,params[:realDate][:day].to_i)
    end
    @date = @realDate.strftime('%Y-%m-%d')
    @games = api_asobal('','').select{|game| game['date'] == @realDate}
  end

  def futsal
    if !params[:realDate]
      @realDate = Time.now()
    else 
      @realDate = Date.new(params[:realDate][:year].to_i,params[:realDate][:month].to_i,params[:realDate][:day].to_i)
    end
    @date = @realDate.strftime('%Y-%m-%d')
    @games = api_futsal('','').select{|game| game['date'] == @realDate}
  end

  def nba_game(gameId)
    game = api_nba('game/boxscore','gameId=' + gameId.to_s)
    game.parsed_response['BoxScore']['Game'] if game
  end

  def football_game(gameId)
    game = Game.find(gameId)
    @date = game.gameTime.strftime('%Y-%m-%d')
    games = api_football('matchsday', 'date=' + @date)
    @games = games.parsed_response['matches'].select{|result| result['id'] == game.externalid}[0] if games.parsed_response['matches']
  end

  def acb_edit
    @realDate = Date.parse(params[:date])
    @games = api_acb('','').select{|game| game['date'] == @realDate}
  end

  def futsal_edit
    @realDate = Date.parse(params[:date])
    @games = api_futsal('','').select{|game| game['date'] == @realDate}
  end

  def asobal_edit
    @realDate = Date.parse(params[:date])
    @games = api_asobal('','').select{|game| game['date'] == @realDate}
  end

  def acb_game(gameId)
    @games = api_acb('','').select{|game| game['id'] == gameId}[0]
  end

  def asobal_game(gameId)
    @games = api_asobal('','').select{|game| game['id'] == gameId}[0]
  end

  def futsal_game(gameId)
    @games = api_futsal('','').select{|game| game['id'] == gameId}[0]
  end

  def nba_edit
    @games = []
    games = api_nba('season/scoreScheduleByDate', 'gameDateOffset=' + params[:date])
    @games = games.parsed_response['Schedule']['League']['Game'] if games.parsed_response['Schedule']['League']['Game']
  end

  def football_edit
    @games = []
    games = api_football('matchsday', 'date=' + params[:date])
    @games = games.parsed_response['matches'] if games.parsed_response
  end

  def close_games
    gamesT = Game.arel_table
    games = Game.where(gamesT[:closed].eq(false).or(gamesT[:closed].eq(nil)))
    games.each do |game|
      if game.externalid and game.gameTime.past?
        if game.typescore == 'Futbol'
          data = football_game(game.id)
          if data['status'].to_i > -1
            result = data['result'].split('-')
            game.score1 = result[0]
            game.score2 = result[1]
          end
          if game.gameTime < 4.hours.ago
            game.closed = true
          end
        end
        if game.typescore == 'Futbol_Sala'
          data = futsal_game(game.externalid)
          if data['homeScore'] != ''
            game.score1 = data['homeScore'].to_i 
            game.score2 = data['awayScore'].to_i
          end
          if game.gameTime < 4.hours.ago
            game.closed = true
          end
        end
        if game.typescore == 'Handball'
          data = asobal_game(game.externalid)
          if data['homeScore'] != ''
            game.score1 = data['homeScore'].to_i - data['awayScore'].to_i
          end
          if game.gameTime < 4.hours.ago
            game.closed = true
          end
        end
        if game.typescore == 'Basquet'
          if game.externalid[0..6] == 'ELMUNDO'
            data = acb_game(game.externalid)
            if data['homeScore'] != ''
              game.score1 = data['homeScore'].to_i - data['awayScore'].to_i
            end
            if game.gameTime < 4.hours.ago
              game.closed = true
            end
          else
            if data = nba_game(game.externalid)
              if data['boxscoreStatus'].to_i > 1
                game.score1 = data['HomeTeam']['Score']['homeScore'].to_i - data['AwayTeam']['Score']['awayScore'].to_i
              end
              if game.gameTime < 4.hours.ago
                game.closed = true
              end
            end 
          end
        end        
        game.save
      end
    end 
  end

  private

  def api_football(req, param)
      base_uri = 'http://www.resultados-futbol.com/scripts/api/api.php'
      key_param = '5cdb0947a37e178f340b78576e90d058'
      format_param = 'json' 
      HTTParty.get("#{base_uri}?key=#{key_param}&format=#{format_param}&req=#{req}&top=true&#{param}") 
  end

  def api_nba(req, param)
    begin 
      HTTParty.get("http://mi.nba.com/statsm/feeds/#{req}.xhtml?tz=GMT0&dst=1&locale=en&#{param}&countryCode=GB") 
    rescue URI::InvalidURIError
    end
  end

  def api_acb(req, param)
    Rails.cache.fetch("api_acb", :expires_in => 1.minute) do
      acb = Nokogiri::HTML(HTTParty.get("http://www.elmundo.es/elmundodeporte/baloncesto/acb/calendario.html").parsed_response)
      parse_el_mundo(acb)
    end
  end

  def api_asobal(req, param)
    Rails.cache.fetch("api_asobal", :expires_in => 1.minute) do
      asobal = Nokogiri::HTML(HTTParty.get("http://www.elmundo.es/elmundodeporte/balonmano/asobal/calendario.html").parsed_response)
      parse_el_mundo(asobal)
    end
  end

  def api_futsal(req, param)
    Rails.cache.fetch("api_futsal", :expires_in => 1.minute) do
      futsal = Nokogiri::HTML(HTTParty.get("http://www.elmundo.es/elmundodeporte/futbol/futbol-sala/calendario.html").parsed_response)
      parse_el_mundo(futsal)
    end  
  end

  def parse_el_mundo(html)
    games = []
    html.css("ul.calendario-jornadas li").each do |jornada|
      dates = jornada.css(".titulo-columna strong").text
      jornada.css("tr").each do |partido|
        game = Hash.new
        date = partido.css(".fecha span").text
        game['date'] = Date.new(dates.split('-')[0].split('.')[2].to_i, date.split('/')[1].to_i, date.split('/')[0].to_i)
        game['home'] = partido.css(".local span").text
        game['away'] = partido.css(".visitante span").text
        game['time'] = partido.css(".hora span").text
        if game['time'] == ""
          game['homeScore'] = partido.css(".marcador strong")[0].text
          game['awayScore'] = partido.css(".marcador strong")[1].text
          game['time']      = '18:00h'
        end
        game['id'] = 'ELMUNDO' + game['home'] + ' ' + game['away']
        games.push(game)
      end
    end
    return games
  end
end

app/helpers/scoreapis_helper.rb
module ScoreapisHelper

end

app/views/scoreapis/acb.html.erb
<div class="page-header">
  <h1><%= link_to "Partits Dia ACB", acb_edit_path(@realDate) %></h1>
  <%= form_tag acb_path, :method => :get do %>
    <%= select_date @realDate, prefix: :realDate %> 
    <%= submit_tag "Find" %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>'Visitant'</th>
      <th>'Local'</th>
      <th>'Resultat'</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game['home'] %></td>
        <td><%= game['away'] %></td>
        <td><%= game['homeScore'] %>  - <%= game['awayScore'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scoreapis/acb_edit.html.erb
<%= form_tag nba_import_path :method => :post do %>

  <div class="page-header">
    <h1>Partits Dia ACB</h1>
    <span>Boxing<%= collection_select(:game, :boxing_id, Boxing.all, :id, :description, options={:include_blank => true, :class => "selectpicker"}) %>
      <%= hidden_field :game, :typescore, :value => 'Acb' %>
      <%= hidden_field :game, :numscore, :value => '1' %>
      <%= hidden_field :game, :numpoint, :value => '3' %>
      <%= hidden_field :game, :secondpoint, :value => '1' %>
    <%= submit_tag "Save" %></span>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>'Id'</th>
        <th>'Visitant'</th>
        <th>'Local'</th>
        <th>'Data'</th>
        <th>'Data'</th>

      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= text_field_tag 'toCreate[][id]', game['id'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][local]', game['home'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][visitor]', game['away'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][date]', game['date'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][time]', game['time'], :readonly => true %></td>
          <td><%= check_box_tag 'toCreate[][create]', true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/scoreapis/asobal.html.erb
<div class="page-header">
  <h1><%= link_to "Partits Dia ASOBAL", asobal_edit_path(@date) %></h1>
  <%= form_tag asobal_path, :method => :get do %>
    <%= select_date @realDate, prefix: :realDate %> 
    <%= submit_tag "Find" %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>'Visitant'</th>
      <th>'Local'</th>
      <th>'Resultat'</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game['home'] %></td>
        <td><%= game['away'] %></td>
        <td><%= game['homeScore'] %>  - <%= game['awayScore'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scoreapis/asobal_edit.html.erb
<%= form_tag asobal_import_path :method => :post do %>

  <div class="page-header">
    <h1>Partits Dia ASOBAL</h1>
    <span>Boxing<%= collection_select(:game, :boxing_id, Boxing.all, :id, :description, options={:include_blank => true, :class => "selectpicker"}) %>
      <%= hidden_field :game, :typescore, :value => 'Handball' %>
      <%= hidden_field :game, :numscore, :value => '1' %>
      <%= hidden_field :game, :numpoint, :value => '3' %>
      <%= hidden_field :game, :secondpoint, :value => '1' %>
    <%= submit_tag "Save" %></span>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>'Id'</th>
        <th>'Visitant'</th>
        <th>'Local'</th>
        <th>'Data'</th>
        <th>'Data'</th>

      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= text_field_tag 'toCreate[][id]', game['id'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][local]', game['home'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][visitor]', game['away'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][date]', game['date'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][time]', game['time'], :readonly => true %></td>
          <td><%= check_box_tag 'toCreate[][create]', true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/scoreapis/football.html.erb
<div class="page-header">
  <h1><%= link_to "Partits Dia Futbol", football_edit_path(@date) %></h1>
  <%= form_tag football_path, :method => :get do %>
    <%= select_date @realDate, prefix: :realDate %> 
    <%= submit_tag "Find" %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>'Local'</th>
      <th>'Visitant'</th>
      <th>'Competicio'</th>
      <th>'Minut'</th>
      <th>'Resultat'</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game['local'] %></td>
        <td><%= game['visitor'] %></td>
        <td><%= game['competition_name'] %></td>
        <td><%= game['live_minute'] %></td>
        <td><%= game['result'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scoreapis/football_edit.html.erb
<%= form_tag football_import_path :method => :post do %>
<div class="page-header">
  <h1>Partits Dia Futbol</h1>      
  <span>Boxing<%= collection_select(:game, :boxing_id, Boxing.all, :id, :description, options={:include_blank => true, :class => "selectpicker"}) %>
  <%= hidden_field :game, :typescore, :value => 'Futbol' %>
  <%= hidden_field :game, :numscore, :value => '2' %>
  <%= hidden_field :game, :numpoint, :value => '3' %>
  <%= hidden_field :game, :secondpoint, :value => '1' %>
  <%= submit_tag "Save" %></span>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>'Id'</th>
      <th>'Local'</th>
      <th>'Visitant'</th>
      <th>'Competicio'</th>
      <th>'Dia'</th>
      <th>'Hora'</th>
      <th>'Minut'</th>
      <th>'Create'</th>  
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
        <tr>
          <td><%= text_field_tag 'toCreate[][id]', game['id'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][local]', game['local'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][visitor]', game['visitor'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][competition_name]', game['competition_name'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][date]', game['date'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][hour]', game['hour'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][minute]', game['minute'], :readonly => true %></td>
          <td><%= check_box_tag 'toCreate[][create]', true %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/scoreapis/futsal.html.erb
<div class="page-header">
  <h1><%= link_to "Partits Dia FUTSAL", futsal_edit_path(@date) %></h1>
  <%= form_tag futsal_path, :method => :get do %>
    <%= select_date @realDate, prefix: :realDate %> 
    <%= submit_tag "Find" %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>'Visitant'</th>
      <th>'Local'</th>
      <th>'Resultat'</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game['home'] %></td>
        <td><%= game['away'] %></td>
        <td><%= game['homeScore'] %>  - <%= game['awayScore'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scoreapis/futsal_edit.html.erb
<%= form_tag futsal_import_path :method => :post do %>

  <div class="page-header">
    <h1>Partits Dia FUTSAL</h1>
    <span>Boxing<%= collection_select(:game, :boxing_id, Boxing.all, :id, :description, options={:include_blank => true, :class => "selectpicker"}) %>
      <%= hidden_field :game, :typescore, :value => 'Futbol_Sala' %>
      <%= hidden_field :game, :numscore, :value => '2' %>
      <%= hidden_field :game, :numpoint, :value => '3' %>
      <%= hidden_field :game, :secondpoint, :value => '1' %>
    <%= submit_tag "Save" %></span>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>'Id'</th>
        <th>'Visitant'</th>
        <th>'Local'</th>
        <th>'Data'</th>
        <th>'Data'</th>

      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= text_field_tag 'toCreate[][id]', game['id'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][local]', game['home'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][visitor]', game['away'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][date]', game['date'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][time]', game['time'], :readonly => true %></td>
          <td><%= check_box_tag 'toCreate[][create]', true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/scoreapis/nba.html.erb
<div class="page-header">
  <h1><%= link_to "Partits Dia NBA", nba_edit_path(@offset) %></h1>
  <%= form_tag nba_path, :method => :get do %>
    <%= select_date @realDate, prefix: :realDate %> 
    <%= submit_tag "Find" %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>'Visitant'</th>
      <th>'Local'</th>
      <th>'Resultat'</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game['AwayTeam']['name'] %></td>
        <td><%= game['HomeTeam']['name'] %></td>
        <td><%= game['AwayTeam']['score'] %>  - <%= game['HomeTeam']['score'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scoreapis/nba_edit.html.erb
<%= form_tag nba_import_path :method => :post do %>

  <div class="page-header">
    <h1>Partits Dia NBA</h1>
    <span>Boxing<%= collection_select(:game, :boxing_id, Boxing.all, :id, :description, options={:include_blank => true, :class => "selectpicker"}) %>
      <%= hidden_field :game, :typescore, :value => 'Basquet' %>
      <%= hidden_field :game, :numscore, :value => '1' %>
      <%= hidden_field :game, :numpoint, :value => '3' %>
      <%= hidden_field :game, :secondpoint, :value => '1' %>
    <%= submit_tag "Save" %></span>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>'Id'</th>
        <th>'Visitant'</th>
        <th>'Local'</th>
        <th>'Data'</th>
        <th>'Data'</th>

      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= text_field_tag 'toCreate[][id]', game['id'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][visitor]', game['AwayTeam']['name'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][local]', game['HomeTeam']['name'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][date]', game['gameDate'], :readonly => true %></td>
          <td><%= text_field_tag 'toCreate[][time]', game['gameTime'], :readonly => true %></td>
          <td><%= check_box_tag 'toCreate[][create]', true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>