config/routes.rb
Nubeporra::Application.routes.draw do

  resources :boxings do
  end

  devise_for :users

  resources :games do
    resources :bets
  end

  resources :scoretypes do
    resources :scoretypevalues
  end

  root :to =>            'static_pages#home'

  get '/home',     to: 'static_pages#home'
  get '/live',     to: 'static_pages#live'
  get '/analysis',     to: 'static_pages#analysis'

  get '/users/:id/bets',  to: 'bets#user'

  get '/boxing/:id/standing',  to: 'boxings#standing', as: :standing_boxing
  get '/boxing/:id/betting',  to: 'boxings#betting', as: :betting_boxing
  post '/boxing/:id/betting',  to: 'boxings#import', as: :boxing_import

  get '/scores/acb',  to: 'scoreapis#acb', as: :acb
  get '/scores/:date/acb/edit',  to: 'scoreapis#acb_edit', as: :acb_edit
  post '/scores/acb/edit',  to: 'games#import', as: :acb_import

  get '/scores/asobal',  to: 'scoreapis#asobal', as: :asobal
  get '/scores/:date/asobal/edit',  to: 'scoreapis#asobal_edit', as: :asobal_edit
  post '/scores/asobal/edit',  to: 'games#import', as: :asobal_import

  get '/scores/futsal',  to: 'scoreapis#futsal', as: :futsal
  get '/scores/:date/futsal/edit',  to: 'scoreapis#futsal_edit', as: :futsal_edit
  post '/scores/futsal/edit',  to: 'games#import', as: :futsal_import

  get '/scores/nba',  to: 'scoreapis#nba', as: :nba
  get '/scores/:date/nba/edit',  to: 'scoreapis#nba_edit', as: :nba_edit
  post '/scores/:date/nba/edit',  to: 'games#import', as: :nba_import

  get '/scores/football',  to: 'scoreapis#football', as: :football

  get '/scores/:date/football/edit',  to: 'scoreapis#football_edit', as: :football_edit
  post '/scores/:date/football/edit',  to: 'games#import', as: :football_import

 

end

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nubeporra</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="/home">NubePorra</a>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Directe", live_path  %></li>
      <li><%= link_to "Analisis", analysis_path  %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Accions <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Boxing", boxings_path  %></li>
          <li><%= link_to "Partits", games_path  %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resultats <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Futbol", football_path %></li>
          <li><%= link_to "NBA", nba_path  %></li>
          <li><%= link_to "ACB", acb_path  %></li>
          <li><%= link_to "ASOBAL", asobal_path  %></li>
          <li><%= link_to "FUTSAL", futsal_path  %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuari <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
          <li><%= link_to "Canvia detalls", edit_user_registration_path  %></li>
          <li><%= link_to "Tanca sessio", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Registra't", new_user_registration_path %></li>
          <li><%= link_to "Inicia sessio", new_user_session_path %></li>
          <% end %>
        </ul>
      </li>
    </ul>
    <div class="navbar-header navbar-right">
        <% if user_signed_in? %>
        <p class="navbar-text"><a href="#">Estas logat com <%= current_user.email %></a></p>
        <% end %>  
    </div>
  </div><!-- /.navbar-collapse -->
</nav>


<div class="container">
  <%= render 'layouts/flash_messages' %>  
  <%= yield %>
</div>

</body>
</html>